apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: realm-keeper-vault
  labels:
    app: realm-keeper-backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: realm-keeper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
